<?php

declare(strict_types=1);

namespace Phpcq\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class UpdateCommand extends Command
{
    protected function configure(): void
    {
        $this->setName('update')->setDescription('Update the phpcq installation');
        parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // TODO: Change the autogenerated stub

        return 0;
    }
}
