<?php

declare(strict_types=1);

namespace Phpcq\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class ValidateCommand extends AbstractCommand
{
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // TODO: Change the autogenerated stub
    }
}
