version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "composer"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
