phpcq:
  repositories:
    - https://phpcq.github.io/repository/repository.json
  directories:
    - src
    - tests
  artifact: .phpcq/build
  tools:
    phpunit:
      version: ^1.0
      signed: false
    psalm:
      version: ^1.0
      signed: false
    composer-require-checker:
      version: ^1.0
      signed: false
    phpmd:
      version: ^1.0
      signed: false
    phpcpd:
      version: ^1.0
      signed: false
    phploc:
      version: ^1.0
      signed: false
    phpcs:
      version: ^1.0
      signed: false
    phpcbf:
      version: ^1.0
      signed: false
    composer-normalize:
      version: ^1.0
      signed: false
  trusted-keys:
    # sb@sebastian-bergmann.de
    - 4AA394086372C20A
    # psalm
    - 8A03EA3B385DBAA1
    # magl@magll.net
    - D2CCAC42F6295E7D
    # PHP_CodeSniffer
    - 31C7E470E2138192
    # Composer normalize
    - C00543248C87FB13

  chains:
    fix:
      composer-normalize:
        dry_run: false
      phpcbf: ~
    verify: &verify
      composer-require-checker: ~
      composer-normalize: ~
    analyze: &analyze
      phploc: ~
      phpcpd: ~
      phpmd: ~
      phpcs: ~
      psalm: ~
      phpunit: ~
    default:
      <<: *verify
      <<: *analyze

tool-config:
  phpunit:

  phpcpd:
  #  exclude:
  #  names:
    names_exclude:
      # These are duplicate code but entirely unrelated to each other.
      - DiffBuilderTest.php
      - AttachmentBuilderTest.php
      - OptionsBuilderTest.php
      - PluginConfigurationBuilderTest.php
  #  regexps_exclude:
  #  log:
  #  min_lines:
  #  min_tokens:
  #  fuzzy: true
  #  custom_flags:

  phploc:

  phpmd:
    ruleset:
      - codesize
      - controversial
      - naming
      - unusedcode

  psalm:

  composer-require-checker:
    config_file: '.composer-require-checker.json'

  phpcs: &phpcs
    standard: PSR12

  phpcbf:
    <<: *phpcs
