#!/usr/bin/env php
<?php

use Phpcq\Runner\Application;
use Phpcq\Runner\Command\ExecCommand;
use Symfony\Component\Console\Input\ArgvInput;

error_reporting(E_ALL & ~ E_USER_DEPRECATED);

function includeIfExists($file)
{
    return file_exists($file) ? include $file : false;
}
if ((!$loader = includeIfExists(__DIR__.'/vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__.'/../../autoload.php'))) {
    echo 'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -sS https://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL;
    exit(1);
}

$application = new Application();

$application->addCommands([
]);

$argv = $_SERVER['argv'];
$input = new ArgvInput($argv);
if ($input->getFirstArgument() === 'exec') {
    $argv = ExecCommand::prepare($argv);
    // strip the application name.
    if ($argv[0] === 'exec') {
        array_shift($argv);
        $application->setDefaultCommand('exec', true);
    }
    $input = new ArgvInput($argv);
}

$application->setAutoExit(true);
$application->run($input);
