#!/usr/bin/env php
<?php

use Phpcq\Command\PlatformInformationCommand;
use Phpcq\Command\RunCommand;
use Phpcq\Command\UpdateCommand;
use Phpcq\Command\ValidateCommand;
use Symfony\Component\Console\Application;

error_reporting(E_ALL & ~ E_USER_DEPRECATED);

function includeIfExists($file)
{
    return file_exists($file) ? include $file : false;
}
if ((!$loader = includeIfExists(__DIR__.'/vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__.'/../../autoload.php'))) {
    echo 'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -sS https://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL;
    exit(1);
}

$application = new Application();

$application->addCommands([
    new RunCommand(),
    new UpdateCommand(),
    new ValidateCommand(),
    new PlatformInformationCommand(),
]);

$application->setAutoExit(true);
$application->run();
